#!/usr/bin/env python3
"""
Unified Python workflow for the VTI DAS MCMC example.

Run from the project root or from any folder inside the project:
    python shell_simple.py

Most experiment-level parameters are controlled here.  Downstream scripts receive
these values through command-line arguments, or read files generated by earlier
steps.  This avoids changing the same parameter in several files.
"""
from __future__ import annotations

from pathlib import Path
import subprocess
import sys
import time


# =============================================================================
# 0. Unified experiment controls: normally only edit this block
# =============================================================================
MASTER_SEED = 0

# qx forward solver.  direct.py writes these values to 01-input/output/control.dat;
# vti_direct.py and vti_joint_mcmc_dram.py receive the same values explicitly.
QX_STOP = 1.0e-6
QX_MAX_ITER = 20

# Noise level used by noise_add.py and written consistently to prop.dat.
OBS_NOISE_STD = 0.001000

# Initial model/source perturbation half widths.
# Source-location initialization is now obtained by grid search using the
# perturbed initial VTI model and the observed qP arrival times.  The source
# perturbation constants are kept only for compatibility with old tests.
INIT_SOURCE_X_STD = 100.0
INIT_SOURCE_Z_STD = 100.0
INIT_GRID_X_MIN = 350.0
INIT_GRID_X_MAX = 1050.0
INIT_GRID_Z_MIN = 350.0
INIT_GRID_Z_MAX = 850.0
INIT_GRID_DX = 25.0
INIT_GRID_DZ = 25.0
INIT_GRID_REFINE = True
INIT_DEP_STD = 20.0
INIT_ALPHA_STD = 500.0
INIT_BETA_STD = 300.0
INIT_EPSILON_STD = 0.2
INIT_GAMMA_STD = 0.2
INIT_DELTA_STD = 0.2

# Prior construction.  Bounds are generated from true + initial files with margins.
# The max-dev values are the MCMC prior limits relative to the initial model.
PRIOR_NMIN = 2
PRIOR_NMAX = 20
PRIOR_SOURCE_MARGIN = 100.0
PRIOR_DEPTH_MARGIN = 0.0
PRIOR_ALPHA_MARGIN = 500.0
PRIOR_BETA_MARGIN = 300.0
PRIOR_ANISO_MARGIN = 0.10
PRIOR_DEPTH_MAX_DEV = 2.0 * INIT_DEP_STD
PRIOR_ALPHA_MAX_DEV = 5.0 * INIT_ALPHA_STD
PRIOR_BETA_MAX_DEV = 5.0 * INIT_BETA_STD
PRIOR_EPSILON_MAX_DEV = 2.0 * INIT_EPSILON_STD
PRIOR_GAMMA_MAX_DEV = 2.0 * INIT_GAMMA_STD
PRIOR_DELTA_MAX_DEV = 2.0 * INIT_DELTA_STD
PRIOR_SOURCE_X_MAX_DEV = 2.0 * INIT_SOURCE_X_STD
PRIOR_SOURCE_Z_MAX_DEV = 2.0 * INIT_SOURCE_Z_STD
PRIOR_NOISE_MAX = max(0.01, 10.0 * OBS_NOISE_STD)
PRIOR_NOISE_STEP = OBS_NOISE_STD / 10.0

# Proposal standard deviations written to prop.dat.
PROP_DEPTH_STD = 10.0
PROP_ALPHA_STD = 100.0
PROP_BETA_STD = 50.0
PROP_EPSILON_STD = 0.005
PROP_GAMMA_STD = 0.005
PROP_DELTA_STD = 0.005
PROP_SOURCE_X_STD = 25.0
PROP_SOURCE_Z_STD = 25.0

# MCMC controls.
MCMC_ITERATIONS = 100000
MCMC_BURNIN = 20000
MCMC_PRINT_EVERY = 100
MCMC_SEED = MASTER_SEED + 100
MCMC_ADAPT_START = 5000
MCMC_ADAPT_INTERVAL = 1000
MCMC_ADAPT_STOP = 0       # 0 means stop at burnin inside MCMC code
MCMC_DR_SCALE = 0.2
MCMC_UPDATE_ORDER = "cyclic"
MCMC_OBJECTIVE = "diff-p-adjacent"
MCMC_USE_WAVES = "P"
MCMC_SIGMA_MODE = "absolute"
INVERT_DEPTHS = True
FIX_LAST_LAYER = True

# Output/plot controls.
FORWARD_VERBOSE_PAIRS = 20
PLOT_HIST_BINS_ANALYSIS = 30
PLOT_HIST_BINS_VEL = 40
PLOT_MAX_SCATTER = 3000


def infer_project_root() -> Path:
    """Find the project root containing 01-input, 02-forward, 04-initial, 05-inversion, 06-result."""
    here = Path(__file__).resolve().parent
    cwd = Path.cwd().resolve()

    candidates = []
    for base in (cwd, here):
        candidates.extend([base, base.parent, base.parent.parent])

    for c in candidates:
        if all((c / d).is_dir() for d in ["01-input", "02-forward", "04-initial", "05-inversion", "06-result"]):
            return c
    return cwd


def run_py(folder: Path, script_name: str, args: list[str | Path | int | float] | None = None) -> None:
    """Run one Python script in a given folder."""
    script = folder / script_name
    if not script.exists():
        raise FileNotFoundError(f"Cannot find script: {script}")
    cmd = [sys.executable, script.name] + [str(a) for a in (args or [])]
    print(f"\n[RUN] cd {folder}")
    print("[RUN] " + " ".join(cmd))
    subprocess.run(cmd, cwd=folder, check=True)


def main() -> int:
    t0 = time.perf_counter()
    root = infer_project_root()
    print(f"[PATH] project root = {root}")

    true_dir = root / "01-input" / "output"
    forward_dir = root / "03-output"
    init_dir = root / "04-initial" / "output"
    result_dir = root / "06-result" / "output"

    # Step 1: true model and control.dat.
    run_py(root / "01-input", "direct.py", [
        "--output-dir", true_dir,
        "--seed", MASTER_SEED,
        "--qx-stop", QX_STOP,
        "--qx-max-iter", QX_MAX_ITER,
    ])

    # Step 2: forward data from the true model.
    run_py(root / "02-forward", "vti_direct.py", [
        "--input-dir", true_dir,
        "--output-dir", forward_dir,
        "--stop", QX_STOP,
        "--max-iter", QX_MAX_ITER,
        "--verbose-pairs", FORWARD_VERBOSE_PAIRS,
    ])

    # Step 3: initial model, noisy observations, source grid-search, prior/proposal.
    # 3a. Perturb only the VTI model.  Source locations are NOT generated by
    # perturbing the true locations.
    run_py(root / "04-initial", "vel_add.py", [
        "--input-file", true_dir / "vel.dat",
        "--output-file", init_dir / "vel.dat",
        "--seed", MASTER_SEED + 2,
        "--dstd", INIT_DEP_STD,
        "--astd", INIT_ALPHA_STD,
        "--bstd", INIT_BETA_STD,
        "--estd", INIT_EPSILON_STD,
        "--gstd", INIT_GAMMA_STD,
        "--delta-std", INIT_DELTA_STD,
    ])
    # 3b. Add Gaussian picking noise to the true forward arrivals.
    run_py(root / "04-initial", "noise_add.py", [
        "--obs-file", forward_dir / "ttime.dat",
        "--output-file", init_dir / "nobs.dat",
        "--seed", MASTER_SEED + 3,
        "--noise-std", OBS_NOISE_STD,
    ])
    # 3c. Estimate initial source locations by coarse qP grid search using the
    # perturbed VTI model and the noisy observations.
    grid_args = [
        "--receiver-geometry", true_dir / "geometry.dat",
        "--init-vel", init_dir / "vel.dat",
        "--obs-file", init_dir / "nobs.dat",
        "--output-file", init_dir / "geo.dat",
        "--x-min", INIT_GRID_X_MIN,
        "--x-max", INIT_GRID_X_MAX,
        "--z-min", INIT_GRID_Z_MIN,
        "--z-max", INIT_GRID_Z_MAX,
        "--dx", INIT_GRID_DX,
        "--dz", INIT_GRID_DZ,
        "--objective", MCMC_OBJECTIVE,
        "--sigma-mode", MCMC_SIGMA_MODE,
        "--qx-stop", QX_STOP,
        "--qx-max-iter", QX_MAX_ITER,
    ]
    if INIT_GRID_REFINE:
        grid_args.append("--refine")
    run_py(root / "04-initial", "geo_grid_search.py", grid_args)

    run_py(root / "04-initial", "prior_prop.py", [
        "--true-geo", true_dir / "geometry.dat",
        "--init-geo", init_dir / "geo.dat",
        "--true-vel", true_dir / "vel.dat",
        "--init-vel", init_dir / "vel.dat",
        "--prior-file", init_dir / "prior.dat",
        "--prop-file", init_dir / "prop.dat",
        "--nmin", PRIOR_NMIN,
        "--nmax", PRIOR_NMAX,
        "--source-margin", PRIOR_SOURCE_MARGIN,
        "--depth-margin", PRIOR_DEPTH_MARGIN,
        "--alpha-margin", PRIOR_ALPHA_MARGIN,
        "--beta-margin", PRIOR_BETA_MARGIN,
        "--aniso-margin", PRIOR_ANISO_MARGIN,
        "--ddep", PRIOR_DEPTH_MAX_DEV,
        "--da", PRIOR_ALPHA_MAX_DEV,
        "--db", PRIOR_BETA_MAX_DEV,
        "--de", PRIOR_EPSILON_MAX_DEV,
        "--dg", PRIOR_GAMMA_MAX_DEV,
        "--dd", PRIOR_DELTA_MAX_DEV,
        "--dh", PRIOR_SOURCE_X_MAX_DEV,
        "--dz", PRIOR_SOURCE_Z_MAX_DEV,
        "--noise-std", OBS_NOISE_STD,
        "--noise-max", PRIOR_NOISE_MAX,
        "--noise-step", PRIOR_NOISE_STEP,
        "--depstd", PROP_DEPTH_STD,
        "--astd", PROP_ALPHA_STD,
        "--bstd", PROP_BETA_STD,
        "--estd", PROP_EPSILON_STD,
        "--gstd", PROP_GAMMA_STD,
        "--dstd", PROP_DELTA_STD,
        "--hstd", PROP_SOURCE_X_STD,
        "--zstd", PROP_SOURCE_Z_STD,
    ])

    # Step 4: inversion.
    mcmc_args = [
        "--input-dir", init_dir,
        "--output-dir", result_dir,
        "--iterations", MCMC_ITERATIONS,
        "--burnin", MCMC_BURNIN,
        "--seed", MCMC_SEED,
        "--use-waves", MCMC_USE_WAVES,
        "--objective", MCMC_OBJECTIVE,
        "--sigma-mode", MCMC_SIGMA_MODE,
        "--qx-stop", QX_STOP,
        "--qx-max-iter", QX_MAX_ITER,
        "--adapt-start", MCMC_ADAPT_START,
        "--adapt-interval", MCMC_ADAPT_INTERVAL,
        "--adapt-stop", MCMC_ADAPT_STOP,
        "--print-every", MCMC_PRINT_EVERY,
        "--dr-scale", MCMC_DR_SCALE,
        "--update-order", MCMC_UPDATE_ORDER,
    ]
    mcmc_args.append("--invert-depths" if INVERT_DEPTHS else "--no-invert-depths")
    if FIX_LAST_LAYER:
        mcmc_args.append("--fix-last-layer")
    run_py(root / "05-inversion", "vti_joint_mcmc_dram.py", mcmc_args)

    # Step 5: analysis/plots.  Burn-in is read from chain.npz by default.
    run_py(root / "06-result", "result_analysis.py", [
        "--root", root,
        "--result-dir", result_dir,
        "--hist-bins", PLOT_HIST_BINS_ANALYSIS,
    ])
    run_py(root / "06-result", "loc_plot.py", [
        "--root", root,
        "--result-dir", result_dir,
        "--max-scatter", PLOT_MAX_SCATTER,
    ])
    run_py(root / "06-result", "vel_plot.py", [
        "--root", root,
        "--result-dir", result_dir,
        "--bins", PLOT_HIST_BINS_VEL,
    ])

    # Step 6: forward predictions from posterior mean and best models,
    # compared with observed qP and station-pair qP data.
    compare_args = [
        "--root", root,
        "--input-dir", init_dir,
        "--result-dir", result_dir,
        "--qx-stop", QX_STOP,
        "--qx-max-iter", QX_MAX_ITER,
        "--objective", MCMC_OBJECTIVE,
        "--sigma-mode", MCMC_SIGMA_MODE,
        "--forward-waves", MCMC_USE_WAVES,
    ]
    compare_args.append("--invert-depths" if INVERT_DEPTHS else "--no-invert-depths")
    if FIX_LAST_LAYER:
        compare_args.append("--fix-last-layer")
    run_py(root / "06-result", "forward_compare_mean_best.py", compare_args)

    elapsed = time.perf_counter() - t0
    print(f"\n[DONE] Total elapsed time: {elapsed:.2f} s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
